VehicleManagement/VehicleManagement/Controllers/VehicleMakeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VehicleManagement.Models;
using VehicleManagement.Service;
using VehicleManagement.Util;

namespace VehicleManagement.Controllers
{
    public class VehicleMakeController : Controller
    {
        private readonly IVehicleMakeService _service;


        public VehicleMakeController(IVehicleMakeService service)
        {
            _service = service;
        }

        
        public async Task<IActionResult> Index(string searchString, string sortOrder, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AbrvSortParm"] = sortOrder == "Abrv" ? "abrv_desc" : "Abrv";

            
            if (searchString!=null)
            {
                pageNumber = 1;
                
            } else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var vehicleMakes = _service.GetAllVehicleMakesAsync().Result.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                
                vehicleMakes = vehicleMakes.Where(v => v.Name.Contains(searchString) || v.Abrv.Contains(searchString));
            }
            vehicleMakes = sortOrder switch
            {
                "name_desc" => vehicleMakes.OrderByDescending(v => v.Name),
                "Abrv" => vehicleMakes.OrderBy(m => m.Abrv),
                "abrv_desc" => vehicleMakes.OrderByDescending(v => v.Abrv),
                _ => vehicleMakes.OrderBy(m => m.Name),
            };

            int pageSize = 3;

        
            return View(await PaginatedList<VehicleMake>.CreateAsync(vehicleMakes.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> Create()
        {
            var vehicleMakes = await _service.GetAllVehicleMakesAsync();
            ViewBag.VehicleMakes = new SelectList(vehicleMakes, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VehicleMake vehicleMake)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    Console.WriteLine(error);
                }

            }
            if (ModelState.IsValid)
            {
                await _service.AddVehicleMakeAsync(vehicleMake);
                return RedirectToAction("Index");
            }


            return View(vehicleMake);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var vehicleMake = await _service.GetVehicleMakeByIdAsync(id);
            if (vehicleMake == null)
            {
                return NotFound();
            }
            return View(vehicleMake);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, VehicleMake vehicleMake)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateVehicleMakeAsync(vehicleMake);
                return RedirectToAction("Index");
            }
            return View(vehicleMake);
        }

        
        public async Task<IActionResult> Delete(int id)
        {
            var vehicleMake = await _service.GetVehicleMakeByIdAsync(id);
            if (vehicleMake == null)
            {
                return NotFound();
            }
            return View(vehicleMake);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            try
            {
                var vehicleMake = await _service.GetVehicleMakeByIdAsync(id);
                if (vehicleMake != null)
                {
                    await _service.DeleteVehicleMakeAsync(id);
                    return RedirectToAction("Index");
                }

                return NotFound();
            }
            catch (DbUpdateException ex)
            {


                TempData["ErrorMessage"] = "Unable to delete VehicleMake. There are related Models in the database.";


                return RedirectToAction("Index");
            }
        }



    }
}

VehicleManagement/VehicleManagement/Controllers/VehicleModelController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using VehicleManagement.Models;
using VehicleManagement.Service;

namespace VehicleManagement.Controllers
{
    public class VehicleModelController : Controller
    {
        private readonly IVehicleModelService _service;
        private readonly IVehicleMakeService _serviceMakes;

        public VehicleModelController(IVehicleModelService service, IVehicleMakeService serviceMakes)
        {
            _service = service;
            _serviceMakes = serviceMakes;
        }
        public async Task<IActionResult> Index()
        {
            var vehicleModels = await _service.GetAllVehicleModelAsync();
            return View(vehicleModels);
        }


        public async Task<IActionResult> Create()
        {


            var vehicleMakes = await _serviceMakes.GetAllVehicleMakesAsync();
          
            ViewBag.VehicleMakes = new SelectList(vehicleMakes, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VehicleModel vehicleModel)
        {


            if (ModelState.IsValid)
            {

                Console.WriteLine("Entering Create POST method");
                Console.WriteLine($"Vehicle Name: {vehicleModel.Name}");
                Console.WriteLine($"Vehicle Abrv: {vehicleModel.Abrv}");
                Console.WriteLine($"VehicleMakeId: {vehicleModel.VehicleMakeId}");

                
                if (vehicleModel.VehicleMakeId == 0)
                {
                    Console.WriteLine("VehicleMakeId is not set properly.");
                }

                await _service.AddVehicleModelAsync(vehicleModel);
                return RedirectToAction("Index");
            }
            Console.WriteLine("ModelState is not valid");

            ViewBag.VehicleMakes = new SelectList(await _serviceMakes.GetAllVehicleMakesAsync(), "Id", "Name");
            return View(vehicleModel);


        }

        
        public async Task<IActionResult> Edit(int id)
        {
            var vehicleModel = await _service.GetVehicleModelByIdAsync(id);
            if (vehicleModel == null)
            {
                return NotFound();
            }
            var vehicleMakes = await _serviceMakes.GetAllVehicleMakesAsync();
            ViewBag.VehicleMakes = new SelectList(vehicleMakes, "Id", "Name");
            return View(vehicleModel);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, VehicleModel vehicleModel)
        {
            if (id != vehicleModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _service.UpdateVehicleModelAsync(vehicleModel);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.VehicleMakes = new SelectList(await _serviceMakes.GetAllVehicleMakesAsync());
            return View(vehicleModel);

        }

        public async Task<IActionResult> Delete(int id)
        {
            var vehicleModel = await _service.GetVehicleModelByIdAsync(id);
            if (vehicleModel == null)
            {
                return NotFound();
            }
            return View(vehicleModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteVehicleModelAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

VehicleManagement/VehicleManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VehicleManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VehicleManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VehicleManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleMake" asp-action="Index">Vehicle Make</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VehicleModel" asp-action="Index">Vehicle Model</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - VehicleManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>